projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.teste_view),
    path('tarefas/', include('tarefas.urls'))
]

tarefas/urls.py
from django.urls import path
from . import views

app_name = 'tarefas'

urlpatterns = [
    path('', views.tarefas_home, name='home'),
    path('adicionar/', views.tarefas_add, name='adicionar'),
    path('remover/<int:id>', views.tarefas_del, name='remover'),
    path('editar/ <int:id>', views.tarefas_up, name='editar')
]

tarefas/models.py
from django.db import models

# Create your models here.
class TarefaModel(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.TextField(null=True, blank=True)
    situacao = models.BooleanField(default=False)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome

tarefas/forms.py
from django import forms
from .models import TarefaModel

class TarefaForm(forms.ModelForm):
    class Meta:
        model = TarefaModel
        fields = [
            'nome',
            'descricao',
            'situacao'
        ]

projeto/views.py
from django.http import HttpResponse

def teste_view(request):
    return HttpResponse('API fucionando!')

tarefas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest
from .forms import TarefaForm
from .models import TarefaModel

# Create your views here.
def tarefas_home(request):
    info = {
        'nome': "Matheus",
        'tarefas': TarefaModel.objects.all()
    }
    return render(request, 'tarefas/home.html', info)

def tarefas_add(request: HttpRequest):
    if request.method == 'POST':
        formulario = TarefaForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('tarefas:home')

    info = {
        'form':TarefaForm
    }
    return render(request, 'tarefas/adicionar.html', info)

def tarefas_del(request: HttpRequest, id: int):
    tarefa = get_object_or_404(TarefaModel, id=id)
    tarefa.delete()
    return redirect('tarefas:home')

def tarefas_up(request: HttpRequest, id: int):
    tarefa = get_object_or_404(TarefaModel, id=id)

    if request.method == 'POST':
        formulario = TarefaForm(request.POST, instance=tarefa)
        if formulario.is_valid():
            formulario.save()
            return redirect('tarefas:home')
        
    formulario = TarefaForm(instance=tarefa)
    info = {
        'form': formulario
    }
    return render(request, 'tarefas/editar.html', info)

templates/tarefas/adicionar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Tarefas</title>
    <style>
        body{
            font-family: sans-serif;
            background-color: #999999;
        }

        h1 {
            font-size: 20pt;
            text-align: center;
            text-shadow: 2px 2px 6px rgb(0,0,0,.6);
        }
        
        input#bot {
            background-color: black;
            color: white;
            top: 280px;
            right: 480px;
            position: absolute;
            text-decoration: none;
            padding: 5px;
        }

        input#bot:hover {
            text-decoration: underline;
        }

        form {
            margin-left: 400px;
        }
    </style>
</head>

<body>
    <h1>Adicione suas tarefas aki!</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Enviar tarefa" id="bot"/>
    </form>
</body>
</html>

templates/tarefas/editar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar tarefa</title>
    <style>
        body{
            font-family: sans-serif;
            background-color: #999999;
        }

        h1 {
            font-size: 20pt;
            text-align: center;
            text-shadow: 2px 2px 6px rgb(0,0,0,.6);
        }
        
        input#bot {
            background-color: black;
            color: white;
            top: 280px;
            right: 480px;
            position: absolute;
            text-decoration: none;
            padding: 5px;
        }

        input#bot:hover {
            text-decoration: underline;
        }

        form {
            margin-left: 400px;
        }
    </style>
</head>

<body>
    <h1>Edite suas tarefas aki!</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Confirmar" id="bot"/>
    </form>
</body>
</html>

templates/tarefas/home.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aprendizado Django</title>
    <style>
        h1 {
            font-size: 20pt;
            font-family: sans-serif;
            text-align: center;
            text-shadow: 2px 2px 6px rgb(0,0,0,.6);
        }

        table.tarefas {
            margin: 0 auto;
        }
        div#centro {
            text-align: center;
            display: block;
            margin-top: 40px;
        }

        table {
            width: 400px;
            height: auto;
            background-color: yellow;
        }

        tbody {
            background-color: black;
            color: white;
        }

        a {
            background-color: black;
            color: white;
            display: block;
            text-decoration: none;
            margin-top: 0px;
            font-family: sans-serif;
            position: relative;

        }

        a:hover {
            text-decoration: underline;
        }

        a#add {
            position: absolute;
            right: 200px;
            padding: 5px;
        }

        td {
            padding: 0px 50px 0px 50px;
            text-align: center;
        }

        th {
            text-indent: 2px;
        }
    </style>
</head>
<body>
    
    <h1>Bem vindo {{nome}}! Aki estão suas tarefas!</h1>
    <div id="centro"></div>
        <table border="1" class="tarefas">
            <thead>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Situação</th>
                <th>Data de criação</th>
            </thead>
            <tbody>
                {% for tarefa in tarefas %}
                    <tr>
                        <td>{{ tarefa.nome }}</td>
                        <td>{{ tarefa.descricao }}</td>
                        <td>{% if tarefa.situacao %}
                                Completa
                            {% else %}
                                Incompleta
                                {% endif %}</td>
                        <td>{{ tarefa.data_criacao }}</td>
                        <td>
                            <a href="{% url 'tarefas:remover' tarefa.id %}">Remover</a>
                        </td>
                        <td>
                            <a href="{% url 'tarefas:editar' tarefa.id %}">Atualizar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <br/>
        <a href="{% url 'tarefas:adicionar' %}" id="add">Adicionar tarefas</a>
    </div>
</body>
</html>